version: '27.5.1'

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "5432:5433"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:Yokona@76@db:5433/mydatabase
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Yokona@76
      POSTGRES_DB: postgres
    ports:
      - "5433:5433"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
